[global]
log_buffer_size = 2048
ring_buffer_size = 256

[handler:console]
type  = console
level = trace
format = default

[handler:file]
type             = file
level            = trace
filename         = app.log
max_file_size    = 104857600
max_backup_files = 10
format = default

[handler:remote]
type     = socket
level    = trace
listener = 127.0.0.1:9000
format = json

[logger:app]
level    = info
handlers = console, file, remote

